version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: falcon
    versions:
    - 2.0.0
  - dependency-name: urllib3
    versions:
    - 1.26.3
  - dependency-name: idna
    versions:
    - "3.1"
